version: "3.8"

services:
  redis: 
    container_name: redis 
    hostname: redis
    build:
      context: ./../
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./../redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redis-commander: 
    container_name: redis-commander
    build:
      context: ./../  
      dockerfile: ./docker/redis-commander/Dockerfile
    environment:
      - REDIS_HOSTS=lk_redis:redis:${REDIS_PORT}
    ports:
      - ${COMMANDER_PORT}:8081
    restart: always
    


